sudo: required

language: perl
perl:
  # - "5.22"
  # - "5.20"
  - "5.18"
  # - "5.16"
  # - "5.14"
  # - "5.12"
  # - "5.10"
  ###- "5.8.8"          # fails due to Number::Format depedancy
  #- "dev"              # installs latest developer release of perl (e.g. 5.21.8)
  #- "blead"            # builds perl from git

env:
  matrix:
    - TARGET=imagemagick

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgcrypt-dev openssl libssh2-1 libssh2-1-dev libnet-ssh2-perl  libjson-any-perl  libperl-dev
  # - wget http://www.imagemagick.org/download/ImageMagick.tar.gz
  # - tar xf ImageMagick.tar.gz
  # - cd ImageMagick*
  # - ./configure --prefix=/usr --with-perl
  # - make
  # - sudo make install
  # - cd ..
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto

matrix:
  allow_failures:
    - perl: blead       # ignore failures for blead perl
  # include:
  #   - perl: "5.20"
  #     env: COVERAGE=1   # enables coverage+coveralls reporting


# os:
#   - linux
# sudo: required
# language: perl
# perl:
#   - "5.10"               # normal preinstalled perl
# before_install:
#   - sudo apt-get -qq update
#   - sudo apt-get install -y   libnet-ssh2-perl libperl-dev libmagickcore-dev openssl libssl-dev
#   - wget http://www.imagemagick.org/download/ImageMagick.tar.gz
#   - tar xf ImageMagick.tar.gz
#   - cd ImageMagick*
#   - ./configure --prefix=/usr --with-perl
#   - make
#   - sudo make install
#   - cd ..
#   - eval $(curl https://travis-perl.github.io/init) --auto
# install:
#   - cpanm --notest --installdeps .
