os:
  - linux
sudo: required
language: perl
perl:
  - "5.10"               # normal preinstalled perl
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y  libperl-dev libmagickcore-dev # to compile some module on travis
  - eval $(curl https://travis-perl.github.io/init) --auto
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --force-yes install libimage-magick-perl libnet-ssh2-perl
  # - wget http://www.imagemagick.org/download/ImageMagick.tar.gz
  # - tar xf ImageMagick.tar.gz
  # - cd ImageMagick*
  # - ./configure --prefix=/usr --with-perl
  # - make
  # - sudo make install
  # - cd ..
install:
  - cpanm --quiet --notest --installdeps .
